// SPDX-License-Identifier: GPL-3.0-or-later
//
// Build one UMD bundle per widget, from the manifest rather than from a list
// kept beside it. package.json's `node-red-dashboard-2.widgets` is what
// Dashboard reads at runtime; anything that enumerates widgets separately is
// a second list to forget to update, and the failure would be a widget that
// registers in Node-RED and renders as nothing on the page.
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const pkg = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const widgets = pkg["node-red-dashboard-2"]?.widgets ?? {};
const entries = Object.entries(widgets);

if (entries.length === 0) {
  process.stderr.write("build-widgets: the manifest lists no widgets\n");
  process.exit(1);
}

/**
 * What Dashboard actually looks for on the page.
 *
 * Its loader does `window[widgetType][componentName]` — the *type* from this
 * manifest is the UMD global, and the component is a **named** export inside
 * it. A bundle that exposes the component as its own global, or only as a
 * default export, loads without a 404 and then throws "component didn't
 * appear to be exported" — or worse, resolves a promise with itself and
 * reports a chaining cycle from inside Dashboard's own bundle, which says
 * nothing about whose fault it is.
 *
 * So each build gets a generated entry that re-exports the component under
 * its name. Generated rather than checked in, because it is derived entirely
 * from the manifest and a hand-written copy is a second list to forget.
 */
const buildDir = fileURLToPath(new URL("../.build/", import.meta.url));
mkdirSync(buildDir, { recursive: true });

for (const [type, { component, output }] of entries) {
  process.stdout.write(`build-widgets: ${component} -> resources/${output} (window[${JSON.stringify(type)}])\n`);
  const entry = `${buildDir}${component}.entry.js`;
  writeFileSync(
    entry,
    "// GENERATED by scripts/build-widgets.mjs. Do not edit.\n"
    + `export { default as ${component} } from "../src/ui/${component}.vue";\n`,
  );
  execFileSync("npx", ["vite", "build", "--mode", "production"], {
    stdio: "inherit",
    env: { ...process.env, WIDGET: component, WIDGET_TYPE: type, WIDGET_ENTRY: entry },
  });
}
