# SPDX-License-Identifier: GPL-2.0
PACKAGE_NAME="imx462-yonder"
PACKAGE_VERSION="1.0.0+60b0f170be23"
BUILT_MODULE_NAME[0]="imx462_yonder"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KERNELRELEASE=${kernelver}"
CLEAN="make KERNELRELEASE=${kernelver} clean"
