// SPDX-License-Identifier: GPL-3.0-or-later
import { describe, expect, it } from "vitest";
import {
  DEV_APP,
  DEV_CAMERA,
  DumlSplitter,
  crc8,
  crc16,
  decodeDuml,
  encodeDuml,
} from "./duml.js";

const bytes = (hex: string): Uint8Array => Uint8Array.from(
  hex.split(/\s+/).filter(Boolean).map((part) => Number.parseInt(part, 16)),
);
const hex = (value: Uint8Array): string => Buffer.from(value).toString("hex");

describe("DUML CRCs", () => {
  // Generated by scripts/pocket2/duml.py, whose tables and seeds come from
  // dji-firmware-tools. These literals deliberately do not use encodeDuml.
  it("matches the Python reference's CRC8 vectors", () => {
    expect(crc8(bytes("55 0d 04"))).toBe(0x33);
    expect(crc8(bytes("55 0f 04"))).toBe(0xa2);
    expect(crc8(bytes("31 32 33 34 35 36 37 38 39"))).toBe(0xfb);
  });

  it("matches the Python reference's CRC16 vectors", () => {
    expect(crc16(bytes("55 0d 04 33 22 01 07 00 20 00 00"))).toBe(0xa716);
    expect(crc16(bytes("55 0d 04 33 22 01 34 12 00 00 0e"))).toBe(0x7e99);
    expect(crc16(bytes("31 32 33 34 35 36 37 38 39"))).toBe(0x7109);
  });
});

describe("DUML frames", () => {
  it("encodes the Python reference frame byte for byte and decodes every field", () => {
    const encoded = encodeDuml({
      commandSet: 2,
      commandId: 0x2c,
      payload: bytes("03 07"),
      sequence: 0xabcd,
    });
    expect(hex(encoded)).toBe("550f04a22201cdab20022c03075e8a");

    expect(decodeDuml(encoded)).toMatchObject({
      length: 15,
      version: 1,
      sender: DEV_APP,
      senderIndex: 1,
      receiver: DEV_CAMERA,
      receiverIndex: 0,
      sequence: 0xabcd,
      response: false,
      ack: 1,
      encryption: 0,
      commandSet: 2,
      commandId: 0x2c,
      payload: bytes("03 07"),
      raw: encoded,
    });
  });

  it("round-trips response, routing, acknowledgement and encryption fields", () => {
    const encoded = encodeDuml({
      commandSet: 4,
      commandId: 0x05,
      payload: bytes("00 7f ff"),
      sequence: 65535,
      sender: 4,
      senderIndex: 7,
      receiver: 2,
      receiverIndex: 3,
      response: true,
      ack: 3,
      encryption: 7,
      version: 12,
    });
    expect(decodeDuml(encoded)).toMatchObject({
      version: 12,
      sender: 4,
      senderIndex: 7,
      receiver: 2,
      receiverIndex: 3,
      sequence: 65535,
      response: true,
      ack: 3,
      encryption: 7,
      commandSet: 4,
      commandId: 0x05,
      payload: bytes("00 7f ff"),
    });
  });

  it("rejects header and body CRC corruption", () => {
    const headerBad = bytes("55 0d 04 32 22 01 07 00 20 00 00 16 a7");
    const bodyBad = bytes("55 0d 04 33 22 01 07 00 20 00 01 16 a7");
    expect(decodeDuml(headerBad)).toBeNull();
    expect(decodeDuml(bodyBad)).toBeNull();
  });

  it("rejects truncated, trailing, impossible-length and non-DUML input", () => {
    const good = bytes("55 0d 04 33 22 01 07 00 20 00 00 16 a7");
    expect(decodeDuml(good.subarray(0, good.length - 1))).toBeNull();
    expect(decodeDuml(Uint8Array.from([...good, 0]))).toBeNull();
    expect(decodeDuml(bytes("55 0c 04 f7 00 00 00 00 00 00 00 00"))).toBeNull();
    expect(decodeDuml(bytes("54 0d 04 33 22 01 07 00 20 00 00 16 a7"))).toBeNull();
  });

  it("refuses values that cannot be represented on the wire", () => {
    expect(() => encodeDuml({ commandSet: 0, commandId: 0, payload: new Uint8Array(1011) }))
      .toThrow(/payload/);
    expect(() => encodeDuml({ commandSet: 256, commandId: 0 })).toThrow(/commandSet/);
    expect(() => encodeDuml({ commandSet: 0, commandId: 0, ack: 4 })).toThrow(/ack/);
    expect(() => encodeDuml({ commandSet: 0, commandId: 0, sequence: -1 })).toThrow(/sequence/);
  });
});

describe("DumlSplitter", () => {
  const first = bytes("55 0d 04 33 22 01 07 00 20 00 00 16 a7");
  const second = bytes("55 0d 04 33 22 01 34 12 00 00 0e 99 7e");

  it("reassembles adjacent frames across every byte boundary", () => {
    for (let cut = 1; cut < first.length; cut += 1) {
      const splitter = new DumlSplitter();
      expect(splitter.push(first.subarray(0, cut))).toEqual([]);
      const parts = splitter.push(Uint8Array.from([...first.subarray(cut), ...second]));
      expect(parts.filter((part) => part.kind === "frame").map((part) => part.frame.sequence))
        .toEqual([7, 0x1234]);
    }
  });

  it("rejects a malformed length and resynchronises on the following frame", () => {
    const splitter = new DumlSplitter();
    const malformed = bytes("55 0c 04 f7 99 88");
    const parts = splitter.push(Uint8Array.from([...malformed, ...first]));
    expect(parts.some((part) => part.kind === "junk")).toBe(true);
    expect(parts.filter((part) => part.kind === "frame").map((part) => part.frame.sequence))
      .toEqual([7]);
    expect(splitter.bufferedBytes).toBe(0);
  });

  it("does not retain an unbounded run of noise", () => {
    const splitter = new DumlSplitter();
    const parts = splitter.push(new Uint8Array(128 * 1024).fill(0x41));
    expect(parts).toHaveLength(1);
    expect(parts[0]).toMatchObject({ kind: "junk" });
    expect(splitter.bufferedBytes).toBe(0);
  });
});
