#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# Grow only the final Yonder media partition on the disk that supplies root.
# A failure is non-fatal to boot: the caller substitutes a read-only empty mount.
set -eu

PATH=/usr/lib/yonder/initramfs-bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH
LC_ALL=C
export LC_ALL

root=${1:?mounted root required}
[ "$root" != / ] && [ -d "$root/etc" ] || exit 2
config=$root/etc/yonder-storage-layout.conf
if [ -f "$config" ] && [ ! -L "$config" ]; then
    parser=/scripts/yonder-storage-layout
    [ -f "$parser" ] || parser=$root/usr/lib/yonder/storage/layout.sh
    # shellcheck disable=SC1090 # installed parser code, not layout data
    . "$parser"
    yonder_read_layout "$config" radxa || exit 1
else
    # Generated by the prototype builder from its partition table.
    # shellcheck disable=SC1091
    . "$root/etc/yonder-storage-prototype.conf"
fi

fail() {
    echo "Yonder media growth: $*" >&2
    exit 1
}

lower() {
    printf '%s' "$1" | tr 'A-F' 'a-f'
}

number() {
    case "$1" in ''|*[!0-9]*) return 1 ;; esac
}

require_uuid() {
    value=$(lower "$1")
    printf '%s\n' "$value" | grep -Eq '^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$'
}

for variable in ROOT_UUID STATE_UUID LOG_UUID MEDIA_UUID DISK_GUID \
        ROOT_PARTUUID STATE_PARTUUID LOG_PARTUUID MEDIA_PARTUUID \
        ROOT_TYPE_GUID STATE_TYPE_GUID LOG_TYPE_GUID MEDIA_TYPE_GUID; do
    eval "value=\${$variable:-}"
    require_uuid "$value" || fail "invalid configured $variable"
done
for variable in ROOT_START ROOT_SIZE STATE_START STATE_SIZE LOG_START LOG_SIZE \
        MEDIA_START MEDIA_MIN_SIZE; do
    eval "value=\${$variable:-}"
    number "$value" || fail "invalid configured $variable"
done
[ "${MEDIA_PARTLABEL:-}" = yonder-media ] || fail 'invalid configured media partition label'

root_device=$(findmnt -n -T "$root" -o SOURCE 2>/dev/null || true)
root_device=${root_device%%\[*}
root_device=$(readlink -f "$root_device" 2>/dev/null || true)
[ -b "$root_device" ] || fail 'mounted root did not resolve to a block device'

partition_number() {
    name=${1##*/}
    [ -r "/sys/class/block/$name/partition" ] || return 1
    cat "/sys/class/block/$name/partition"
}

parent_disk() {
    parent=$(lsblk -dn -o PKNAME "$1" 2>/dev/null || true)
    [ -n "$parent" ] || return 1
    printf '/dev/%s\n' "$parent"
}

disk=$(parent_disk "$root_device") || fail 'cannot identify the disk supplying root'
[ -b "$disk" ] || fail 'root parent is not a block device'

# Refuse layouts with any additional partition. Paths contain no whitespace.
# The exact five NAME/TYPE records are the disk plus p1-p4.
# shellcheck disable=SC2046 # deliberate tokenization of controlled lsblk fields
set -- $(lsblk -nrpo NAME,TYPE "$disk")
case "${2:-}" in disk|loop) parent_type_valid=1 ;; *) parent_type_valid=0 ;; esac
[ "$#" -eq 10 ] && [ "$1" = "$disk" ] && [ "$parent_type_valid" -eq 1 ] || \
    fail 'boot disk is not the expected four-partition layout'
shift 2
root_partition=''
state_device=''
log_device=''
media_device=''
while [ "$#" -gt 0 ]; do
    [ "$2" = part ] || fail 'unexpected non-partition child on the boot disk'
    case "$(partition_number "$1")" in
        1) root_partition=$1 ;;
        2) state_device=$1 ;;
        3) log_device=$1 ;;
        4) media_device=$1 ;;
        *) fail 'boot disk has an unexpected partition number' ;;
    esac
    shift 2
done
[ "$root_partition" = "$root_device" ] \
    && [ -b "$state_device" ] && [ -b "$log_device" ] && [ -b "$media_device" ] \
    || fail 'mounted root is not p1 of the expected p1-p4 layout'
[ -z "$(findmnt -rn -S "$media_device" -o TARGET 2>/dev/null || true)" ] \
    || fail 'media partition is already mounted'
[ "$(lower "$(blkid -s UUID -o value "$root_device" 2>/dev/null || true)")" = "$(lower "$ROOT_UUID")" ] \
    || fail 'mounted root filesystem UUID does not match this image'

sysfs_value() {
    name=${1##*/}
    field=$2
    [ -r "/sys/class/block/$name/$field" ] || return 1
    cat "/sys/class/block/$name/$field"
}

check_fixed_partition() {
    device=$1
    expected_start=$2
    expected_size=$3
    expected_uuid=$4
    [ "$(sysfs_value "$device" start)" = "$expected_start" ] || return 1
    [ "$(sysfs_value "$device" size)" = "$expected_size" ] || return 1
    [ "$(lower "$(blkid -s PARTUUID -o value "$device" 2>/dev/null || true)")" = "$(lower "$expected_uuid")" ] || return 1
}

check_fixed_partition "$root_device" "$ROOT_START" "$ROOT_SIZE" "$ROOT_PARTUUID" \
    || fail 'root partition geometry or identity differs from this image'
check_fixed_partition "$state_device" "$STATE_START" "$STATE_SIZE" "$STATE_PARTUUID" \
    || fail 'state partition geometry or identity differs from this image'
check_fixed_partition "$log_device" "$LOG_START" "$LOG_SIZE" "$LOG_PARTUUID" \
    || fail 'log partition geometry or identity differs from this image'
media_size=$(sysfs_value "$media_device" size)
number "$media_size" || fail 'cannot read media partition size'
[ "$(sysfs_value "$media_device" start)" = "$MEDIA_START" ] \
    && [ "$media_size" -ge "$MEDIA_MIN_SIZE" ] \
    && [ "$(lower "$(blkid -s PARTUUID -o value "$media_device" 2>/dev/null || true)")" = "$(lower "$MEDIA_PARTUUID")" ] \
    || fail 'media partition geometry or identity differs from this image'
for pair in "$state_device:$STATE_UUID" "$log_device:$LOG_UUID" "$media_device:$MEDIA_UUID"; do
    device=${pair%%:*}
    expected=${pair#*:}
    [ "$(lower "$(blkid -s UUID -o value "$device" 2>/dev/null || true)")" = "$(lower "$expected")" ] \
        && [ "$(blkid -s TYPE -o value "$device" 2>/dev/null || true)" = ext4 ] \
        || fail 'durable filesystem type or UUID differs from this image'
done
[ "$(blockdev --getss "$disk")" = 512 ] || fail 'boot disk logical sector size is not 512 bytes'

gpt_field() {
    partition=$1
    label=$2
    sgdisk -i "$partition" "$disk" 2>/dev/null | sed -n "s/^$label: //p"
}

check_gpt_identity() {
    [ "$(lower "$(sgdisk -p "$disk" 2>/dev/null | sed -n 's/^Disk identifier (GUID): //p')")" = "$(lower "$DISK_GUID")" ] || return 1
    partition=1
    for expected in "$ROOT_PARTUUID:$ROOT_TYPE_GUID" "$STATE_PARTUUID:$STATE_TYPE_GUID" \
            "$LOG_PARTUUID:$LOG_TYPE_GUID" "$MEDIA_PARTUUID:$MEDIA_TYPE_GUID"; do
        expected_uuid=${expected%%:*}
        expected_type=${expected#*:}
        [ "$(lower "$(gpt_field "$partition" 'Partition unique GUID')")" = "$(lower "$expected_uuid")" ] || return 1
        actual_type=$(gpt_field "$partition" 'Partition GUID code')
        actual_type=${actual_type%% *}
        [ "$(lower "$actual_type")" = "$(lower "$expected_type")" ] || return 1
        partition=$((partition + 1))
    done
    [ "$(gpt_field 4 'Partition name')" = "'$MEDIA_PARTLABEL'" ] || return 1
}

gpt_report_clean() {
    grep -q 'No problems found' "$1" \
        && ! grep -Eq 'Creating new GPT|corrupt GPT|invalid .*GPT|CRCs don.t match|ERROR|Problem:|Identified [1-9]' "$1"
}

gpt_has_valid_copy() {
    # A completely clean report means both CRC-checked copies were read. With
    # one damaged copy, sgdisk prints the per-copy header/table status below.
    # A larger flashed disk has two valid copies at the image geometry, plus
    # only the specific stale-secondary-location problem accepted here.
    if gpt_report_clean "$1"; then
        return 0
    fi
    if grep -q '^Main header: OK$' "$1" && grep -q '^Main partition table: OK$' "$1"; then
        return 0
    fi
    if grep -q '^Backup header: OK$' "$1" && grep -q '^Backup partition table: OK$' "$1"; then
        return 0
    fi
    grep -q "secondary header's self-pointer indicates that it doesn't reside" "$1" \
        && ! grep -Eq 'Creating new GPT|corrupt GPT|invalid .*GPT|CRCs don.t match|ERROR' "$1"
}

gpt_report=/run/yonder-grow-media-gpt.txt
if ! sgdisk -v "$disk" >"$gpt_report" 2>&1; then
    fail 'neither GPT copy could be safely validated'
fi
gpt_has_valid_copy "$gpt_report" || fail 'no CRC-valid GPT header and partition-table copy remains'
check_gpt_identity || fail 'validated GPT copy does not describe this image'
if ! gpt_report_clean "$gpt_report"; then
    # `sgdisk -e` writes corrected primary/backup metadata from the validated
    # in-memory table and moves the backup to the physical end when necessary.
    # It does not make the two writes atomic; a later boot repeats validation.
    sgdisk -e "$disk" >/run/yonder-grow-media-repair.txt 2>&1 \
        || fail 'could not repair or relocate the backup GPT'
    sync -f "$disk"
    blockdev --flushbufs "$disk"
    check_gpt_identity || fail 'GPT identity changed while repairing metadata'
    sgdisk -v "$disk" >"$gpt_report" 2>&1 || fail 'GPT repair did not validate'
    gpt_report_clean "$gpt_report" || fail 'GPT repair left unresolved errors'
    [ "${YONDER_GROW_STOP_AFTER:-}" != gpt-repair ] || fail 'test interruption after GPT repair'
fi

disk_sectors=$(blockdev --getsz "$disk")
number "$disk_sectors" || fail 'cannot read boot disk size'
usable_bounds=$(sgdisk -p "$disk" 2>/dev/null | \
    sed -n 's/^First usable sector is \([0-9]*\), last usable sector is \([0-9]*\)$/\1 \2/p')
# shellcheck disable=SC2086 # exactly two numeric fields from the anchored match
set -- $usable_bounds
[ "$#" -eq 2 ] || fail 'cannot determine GPT usable-sector bounds'
first_usable=$1
desired_end=$2
if ! number "$first_usable" || ! number "$desired_end"; then
    fail 'invalid GPT usable-sector bounds'
fi
# The locked Armbian GPT leaves sectors 34-2047 available for opaque board
# boot data. sgdisk preserves the corresponding 2048-sector reserve when it
# relocates the backup metadata. A conventional GPT has a 34-sector reserve.
# Accept the CRC-validated runtime bound only when both ends are symmetric and
# the metadata reserve remains within those known layouts.
tail_reserve=$((disk_sectors - desired_end))
[ "$first_usable" -ge 34 ] && [ "$first_usable" -le 2048 ] \
    && [ "$tail_reserve" -eq "$first_usable" ] \
    || fail 'unexpected GPT metadata geometry'
media_size=$(sysfs_value "$media_device" size)
media_end=$((MEDIA_START + media_size - 1))
[ "$media_end" -le "$desired_end" ] || fail 'media partition extends beyond the usable disk'
if [ "$media_end" -lt "$desired_end" ]; then
    # This is one in-memory GPT transaction. The fixed start, type, unique GUID
    # and name are restored explicitly; the disk GUID and p1-p3 are untouched.
    sgdisk --delete=4 --new="4:${MEDIA_START}:0" \
        --typecode="4:${MEDIA_TYPE_GUID}" \
        --partition-guid="4:${MEDIA_PARTUUID}" \
        --change-name="4:${MEDIA_PARTLABEL}" "$disk" >/dev/null \
        || fail 'could not extend the final media partition'
    sync -f "$disk"
    blockdev --flushbufs "$disk"
    check_gpt_identity || fail 'partition identity changed while extending media'
    sgdisk -v "$disk" >"$gpt_report" 2>&1 || fail 'extended GPT did not validate'
    gpt_report_clean "$gpt_report" || fail 'extended GPT has unresolved errors'
    partx --update --nr 4 "$disk" >/dev/null || fail 'kernel did not accept the extended media partition'
    media_size=$(sysfs_value "$media_device" size)
    [ "$((MEDIA_START + media_size - 1))" -eq "$desired_end" ] \
        || fail 'kernel media geometry did not reach the GPT boundary'
    # devtmpfs/udev normally keeps the existing partition node current. Loop
    # devices can receive a new dynamic minor after partx; repair that exact,
    # already-validated node from its sysfs dev_t so the same boot can proceed.
    node_size=$(blockdev --getsz "$media_device" 2>/dev/null || true)
    if [ "$node_size" != "$media_size" ]; then
        device_numbers=$(sysfs_value "$media_device" dev) || fail 'cannot read refreshed media device number'
        major=${device_numbers%:*}
        minor=${device_numbers#*:}
        if ! number "$major" || ! number "$minor"; then
            fail 'invalid refreshed media device number'
        fi
        replacement=$media_device.yonder-new
        [ ! -e "$replacement" ] || fail 'temporary media device path already exists'
        mknod "$replacement" b "$major" "$minor" || fail 'cannot create refreshed media device node'
        chmod 0600 "$replacement"
        mv "$replacement" "$media_device"
        [ "$(blockdev --getsz "$media_device")" = "$media_size" ] \
            || fail 'refreshed media device node has the wrong size'
    fi
    [ "${YONDER_GROW_STOP_AFTER:-}" != partition ] || fail 'test interruption after partition growth'
fi

filesystem_bytes() {
    header=$(dumpe2fs -h "$1" 2>/dev/null) || return 1
    block_count=$(printf '%s\n' "$header" | sed -n 's/^Block count:[[:space:]]*//p')
    block_size=$(printf '%s\n' "$header" | sed -n 's/^Block size:[[:space:]]*//p')
    number "$block_count" && number "$block_size" || return 1
    printf '%s\n' "$((block_count * block_size))"
}

fs_bytes=$(filesystem_bytes "$media_device") || fail 'cannot inspect the media ext4 filesystem'
partition_bytes=$((media_size * 512))
[ "$fs_bytes" -le "$partition_bytes" ] || fail 'media filesystem exceeds its partition'
if [ "$((partition_bytes - fs_bytes))" -ge 4096 ]; then
    set +e
    e2fsck -pf "$media_device"
    check_status=$?
    set -e
    [ "$check_status" -le 1 ] || fail "media filesystem check returned $check_status"
    resize2fs "$media_device" >/dev/null || fail 'media filesystem growth failed'
    sync -f "$media_device"
    blockdev --flushbufs "$media_device"
    [ "${YONDER_GROW_STOP_AFTER:-}" != filesystem ] || fail 'test interruption after filesystem growth'
    fs_bytes=$(filesystem_bytes "$media_device") || fail 'cannot verify the grown media filesystem'
    [ "$fs_bytes" -le "$partition_bytes" ] \
        && [ "$((partition_bytes - fs_bytes))" -lt 4096 ] \
        || fail 'media filesystem did not fill the extended partition'
fi

echo 'Yonder media growth: final partition and ext4 filesystem are ready.'
