// SPDX-License-Identifier: GPL-3.0-or-later
import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { writeFileDurable } from "../fs/durable.js";
import type { Config } from "../schema/config.js";

export const DNSMASQ_DROPIN = "/etc/NetworkManager/dnsmasq-shared.d/yonder.conf";

/**
 * NetworkManager's `shared` method runs its own dnsmasq for the access point.
 * This drop-in sets the pool. One fewer daemon than a standalone dnsmasq, and
 * NetworkManager owns the lifecycle.
 */
export function renderDnsmasqConf(config: Config): string {
  const { start, end, lease } = config.network.ap.dhcp;
  return [
    "# Generated by yonder-core from /etc/yonder/config.yaml.",
    "# Edits here are overwritten on the next apply.",
    `dhcp-range=${start},${end},${lease}`,
    "dhcp-authoritative",
    "",
  ].join("\n");
}

export function writeDnsmasqConf(path: string, config: Config): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileDurable(path, renderDnsmasqConf(config), 0o644);
}
