// SPDX-License-Identifier: GPL-3.0-or-later
import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const base=process.env.COCKPIT_URL||'http://127.0.0.1:4192';
const artifacts=fileURLToPath(new URL('../.cockpit-artifacts/',import.meta.url));await mkdir(artifacts,{recursive:true});
const browser=await chromium.launch();const page=await browser.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.route('**/cockpit/api/**',route=>route.abort('blockedbyclient'));
for(const [name,width,height] of [['laptop',1440,900],['tablet',1024,768],['portrait',768,1024],['phone',390,844]]){
 await page.setViewportSize({width,height});await page.goto(base);await page.getByRole('main').waitFor();
 assert.equal(await page.getByRole('main').getAttribute('data-layout'),'full');
 const pfd=page.locator('[aria-label="Primary flight display"]');assert.equal(await pfd.count(),1);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 const skid=page.getByRole('button',{name:'Slip and skid indicator settings',exact:true});
 await skid.waitFor({state:'visible'});
 assert.equal(await skid.locator('.skid-ball').count(),1);
 assert.equal(await page.locator('.pfd-standard-rate-bank path').count(),2);
 assert.equal(await page.locator('.turn-tick').count(),4);
 const ballBounds=await skid.locator('.skid-ball').boundingBox(), headingBounds=await page.locator('.pfd-heading-value').boundingBox();
 assert.ok(ballBounds.y+ballBounds.height<headingBounds.y,'ball sits above the HSI heading readout');
 const samples=await page.evaluate(async()=>{
   const result=[];
   for(let i=0;i<15;i++){result.push({ball:!!document.querySelector('.skid-ball'),turnMissing:!!document.querySelector('.turn-unavailable')});await new Promise(r=>setTimeout(r,50));}
   return result;
 });
 assert.ok(samples.every(s=>s.ball&&!s.turnMissing),'new zero-age packets must not flash unavailable between UI clock ticks');
 await skid.click();await page.getByRole('dialog',{name:'Slip / skid',exact:true}).waitFor();
 await page.getByRole('button',{name:'Close PFD controls'}).click();
 const wind=page.getByRole('button',{name:'Wind display settings',exact:true});
 await wind.waitFor({state:'visible'});
 assert.equal(await wind.locator('[data-direction="down"]').count(),1);
 assert.equal(await wind.locator('[data-direction="left"]').count(),1);
 // Verify the actual hit target at each responsive size, not merely SVG presence.
 await wind.click();await page.getByRole('dialog',{name:'Wind display',exact:true}).waitFor();
 await page.getByLabel('Wind display mode',{exact:true}).selectOption('direction');
 await page.getByRole('button',{name:'Close PFD controls'}).click();
 assert.match(await wind.innerText(),/225° T/);
 await wind.click();await page.getByLabel('Wind display mode',{exact:true}).selectOption('components');
 await page.getByRole('button',{name:'Close PFD controls'}).click();
 await page.screenshot({path:`${artifacts}/${name}-full.png`});
 if(width>=768){
  await page.getByRole('button',{name:'Expand mission',exact:true}).click();assert.equal(await page.getByRole('main').getAttribute('data-layout'),'mission');
  const course=await page.locator('.pfd-course-pointer').getAttribute('transform');
  await page.evaluate(()=>window.cockpitFixture.leg(3,-25));
  await page.locator('[data-mission-seq="3"][aria-current="step"]').waitFor();
  assert.equal(await page.locator('.mission-leg-connector').getAttribute('data-from'),'2');
  assert.equal(await page.locator('.mission-leg-connector').getAttribute('data-to'),'3');
  assert.match(await page.locator('.cockpit-mission-summary').innerText(),/WP02 → WP03.*NEXT IN PLAN WP04/s);
  assert.notEqual(await page.locator('.pfd-course-pointer').getAttribute('transform'),course);
  assert.ok(Number(await page.locator('.pfd-cdi-bar').getAttribute('x1'))>0);
  assert.equal(await page.locator('.cdi-moving-bar').getAttribute('transform'),'translate(108.6 0)');
  await page.evaluate(()=>window.cockpitFixture.leg(9));
  await page.locator('[data-mission-seq="9"][aria-current="step"]').waitFor();
  const followed=await page.locator('.cockpit-mission-list').evaluate(list=>{const row=list.querySelector('[aria-current="step"]'),a=row.getBoundingClientRect(),b=list.getBoundingClientRect();return list.scrollTop>0&&a.top>=b.top-1&&a.bottom<=b.bottom+1});
  assert.ok(followed,'active waypoint follows into view when the mission advances');
  await page.locator('.cockpit-mission-list').dispatchEvent('wheel',{deltaY:-100});
  assert.equal(await page.getByRole('button',{name:'Follow active mission leg',exact:true}).getAttribute('aria-pressed'),'false');
  await page.getByRole('button',{name:'Follow active mission leg',exact:true}).click();
  await page.screenshot({path:`${artifacts}/${name}-mission.png`});
  await page.getByRole('button',{name:'Edit altitude at waypoint 9',exact:true}).click();
  await page.getByLabel('Alt parameter 7',{exact:true}).fill('600');
  await page.getByRole('button',{name:'Save draft item',exact:true}).click();
  assert.match(await page.locator('.cockpit-mission-summary').innerText(),/LOCAL DRAFT/);
  assert.match(await page.getByRole('button',{name:'Edit altitude at waypoint 9',exact:true}).innerText(),/600 FT/);
  assert.equal(await page.locator('.mission-leg-connector').count(),0);
  await page.getByRole('button',{name:'Mission controls',exact:true}).click();
  await page.getByRole('button',{name:/Show aircraft mission Return to the received mission/}).click();
  await page.getByRole('button',{name:'Show terrain profile',exact:true}).click();
  assert.equal(await page.getByRole('region',{name:'Mission terrain profile',exact:true}).count(),1);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.getByRole('button',{name:'Waypoints',exact:true}).click();
  await page.evaluate(()=>window.cockpitFixture.leg(2));
  await page.getByRole('button',{name:'Return to full PFD',exact:true}).click();
 }
 await page.getByRole('button',{name:'Airspeed controls',exact:true}).click();await page.getByRole('dialog',{name:'Airspeed reference',exact:true}).waitFor();await page.screenshot({path:`${artifacts}/${name}-airspeed.png`});await page.getByRole('button',{name:'Close PFD controls'}).click();
 if(name==='laptop'){
  await page.getByRole('button',{name:'Attitude and display settings',exact:true}).click();
  await page.getByLabel('Speed units',{exact:true}).selectOption('mph');
  await page.getByLabel('Vertical speed units',{exact:true}).selectOption('mps');
  await page.getByRole('button',{name:'Close PFD controls',exact:true}).click();
  assert.match(await page.locator('.pfd-svg').textContent(),/MPH/);
  assert.match(await page.locator('.pfd-wind-display').textContent(),/MPH/);
  await page.getByRole('button',{name:'Altitude / Speed',exact:true}).click();
  await page.getByLabel('Requested altitude FT',{exact:true}).fill('500');
  await page.getByLabel('Vertical speed units',{exact:true}).selectOption('fpm');
  await page.getByLabel('Requested vertical rate',{exact:true}).fill('300');
  await page.getByLabel('Altitude units',{exact:true}).selectOption('m');
  assert.equal(await page.getByLabel('Requested altitude M',{exact:true}).inputValue(),'152.4');
  await page.getByLabel('Altitude units',{exact:true}).selectOption('ft');
  await page.getByLabel('Speed units',{exact:true}).selectOption('kt');
  await page.getByRole('button',{name:'Close flight controls',exact:true}).click();
 }
 assert.equal(await page.evaluate(()=>window.cockpitFixture.calls.length),0);
}
await page.setViewportSize({width:1440,height:900});await page.goto(base);
await page.getByRole('button',{name:'Wind display settings',exact:true}).click();
await page.getByLabel('Wind display mode',{exact:true}).selectOption('off');
await page.getByRole('button',{name:'Close PFD controls'}).click();
assert.equal(await page.locator('.pfd-wind-display').count(),0);
await page.reload();assert.equal(await page.locator('.pfd-wind-display').count(),0);
await page.getByRole('button',{name:'PFD Menu',exact:true}).click();
await page.getByRole('button',{name:'Wind Components · arrow · direction',exact:true}).click();
await page.getByLabel('Wind display mode',{exact:true}).selectOption('components');
await page.getByRole('button',{name:'Close PFD controls'}).click();
await page.getByRole('button',{name:'Mission controls',exact:true}).click();await page.getByRole('button',{name:'Add mission item',exact:false}).click();assert.match(await page.locator('.mission-touch').innerText(),/55/);await page.getByRole('searchbox',{name:'Search mission commands'}).fill('Loiter');await page.screenshot({path:`${artifacts}/catalog.png`});await page.getByRole('button',{name:'Close mission controls'}).click();
await page.getByRole('button',{name:'Display & data',exact:true}).click();await page.getByLabel('Palette',{exact:true}).selectOption('day');await page.screenshot({path:`${artifacts}/day-settings.png`});await page.getByRole('button',{name:'Close cockpit panel'}).click();await page.screenshot({path:`${artifacts}/day-full.png`});
assert.equal(await page.locator('.pfd-hotspot').evaluateAll(nodes=>nodes.every(node=>getComputedStyle(node).backgroundColor==='rgba(0, 0, 0, 0)')),true,'day palette must preserve transparent instrument hit regions');
await page.waitForTimeout(1000);const markerCount=await page.locator('.leaflet-tooltip').count();await page.waitForTimeout(1200);assert.equal(await page.locator('.leaflet-tooltip').count(),markerCount);assert.equal(markerCount,13);
await page.getByRole('button',{name:'Expand map',exact:true}).click();
const ownTrail=page.locator('path.cockpit-own-trail');await ownTrail.waitFor({state:'attached'});
assert.match(await ownTrail.getAttribute('d'),/L/,'ownship breadcrumb geometry must render');
const trailWidthBefore=await ownTrail.evaluate(node=>node.getBBox().width);
assert.equal(await page.getByRole('button',{name:'Fit traffic range',exact:true}).count(),1,'traffic range needs a map framing control');
await page.getByRole('button',{name:'Fit traffic range',exact:true}).click();
await page.waitForTimeout(1200);
assert.ok(await ownTrail.evaluate(node=>node.getBBox().width)<trailWidthBefore/4,'Follow must preserve the wider traffic view across telemetry updates');
const fittedWidth=await ownTrail.evaluate(node=>node.getBBox().width);
await page.getByRole('button',{name:'Zoom map out',exact:true}).click();
await page.waitForTimeout(1200);
assert.ok(await ownTrail.evaluate(node=>node.getBBox().width)<=fittedWidth,'Follow must not reset manually selected zoom');
await page.getByRole('button',{name:'Aircraft breadcrumb settings',exact:true}).click();
await page.getByLabel('Aircraft trail window',{exact:true}).selectOption('distance');
await page.getByLabel('Aircraft trail distance units',{exact:true}).selectOption('mi');
await page.getByLabel('Aircraft trail distance',{exact:true}).fill('2');
await page.getByLabel('Aircraft trail distance',{exact:true}).dispatchEvent('change');
await page.getByLabel('Aircraft trail window',{exact:true}).selectOption('power');
await page.screenshot({path:`${artifacts}/own-trail-settings.png`});
await page.getByRole('button',{name:'Clear displayed trail',exact:true}).click();
await page.getByRole('button',{name:'Close cockpit panel'}).click();
assert.doesNotMatch(await ownTrail.getAttribute('d'),/L/,'clear affects the actual map path');
await page.getByRole('button',{name:'Aircraft breadcrumb settings',exact:true}).click();
await page.getByRole('button',{name:'Restore recorded trail',exact:true}).click();
await page.getByRole('button',{name:'Close cockpit panel'}).click();
assert.match(await ownTrail.getAttribute('d'),/L/);
await page.screenshot({path:`${artifacts}/own-trail-map.png`});
await page.setViewportSize({width:1024,height:768});await page.screenshot({path:`${artifacts}/own-trail-tablet.png`});
assert.equal(await page.evaluate(()=>window.cockpitFixture.calls.length),0);
assert.deepEqual(errors,[]);await browser.close();console.log('Cockpit fixture browser checks passed; no vehicle requests. Artifacts: '+artifacts);
