// SPDX-License-Identifier: GPL-3.0-or-later
import {expect,it,vi} from 'vitest';
import {mount} from '@vue/test-utils';
import YonderCockpit from '../YonderCockpit.vue';
import {fixture} from '../../../cockpit/fixture.mjs';
function host(){const report=fixture();report.capabilities.flightControl=['heading','altitude','speed','loiter'].map(kind=>({kind,available:true}));return mount(YonderCockpit,{props:{id:'flight-host-test',report,api:{command:vi.fn(async()=>({accepted:true,operationId:'one'}))}},global:{stubs:{YonderCockpitMap:true,YonderPicture:true,TerrainVision:true}}})}
it('reviews a persistent heading request then sends exactly once on confirmation',async()=>{const w=host();await w.get('[aria-label="Heading"]').trigger('click');await w.get('[aria-label="Requested true heading"]').setValue('125');const api=w.props('api');expect(api.command).not.toHaveBeenCalled();await w.get('.flight-request-form').trigger('submit');expect(w.get('[aria-label="Review aircraft command"]').text()).toContain('125° true');expect(api.command).not.toHaveBeenCalled();await w.get('.cockpit-confirm').trigger('click');expect(api.command).toHaveBeenCalledTimes(1);expect(api.command.mock.calls[0][0].action).toMatchObject({kind:'heading',headingDeg:125,reference:'true'});w.unmount()});
it('picks a Direct-To map target without creating a local mission draft',async()=>{const w=host();await w.get('[aria-label="Direct-To"]').trigger('click');await w.get('.flight-control-dialog .mission-touch-wide').trigger('click');expect(w.attributes('data-layout')).toBe('map');expect(w.findComponent({name:'YonderCockpitMap'}).props('picking')).toBe(true);w.findComponent({name:'YonderCockpitMap'}).vm.$emit('location',{lat:35.123,lon:-84.456});await w.vm.$nextTick();expect(w.get('[aria-label="Target latitude"]').element.value).toBe('35.123');expect(w.get('[aria-label="Target longitude"]').element.value).toBe('-84.456');expect(w.vm.draft).toBeNull();expect(w.props('api').command).not.toHaveBeenCalled();w.unmount()});
it('does not send while flight details are recovering and offers camera fallback',async()=>{const w=host();await w.setProps({report:{...w.props('report'),_detailsReady:false}});expect(w.vm.canCommand).toBe(false);w.vm.background='camera';await w.vm.$nextTick();await w.get('[aria-label="Use synthetic terrain"]').trigger('click');expect(w.vm.background).toBe('terrain');expect(w.vm.onlineTerrain).toBe(true);expect(w.props('api').command).not.toHaveBeenCalled();w.unmount()});
it('replaces its queued notice when the matching aircraft result arrives',async()=>{const w=host();await w.vm.sendReadAction('mission-download');expect(w.vm.error).toContain('queued');await w.setProps({report:{...w.props('report'),operations:[{id:'one',action:{kind:'mission-download'},state:'observed',message:'Complete vehicle mission downloaded'}]}});expect(w.vm.error).toBe('observed · Complete vehicle mission downloaded');w.unmount()});
