// SPDX-License-Identifier: GPL-3.0-or-later
import {it,expect} from 'vitest';
const path='./terrain-adapter.mjs';const adapter=await import(/* @vite-ignore */path).catch(()=>null);
const tile={descriptor:{id:'sample',columns:3,rows:3,spacingM:1,originEastingM:500000,originNorthingM:4000000},groundM:new Float32Array([10,11,12,11,12,13,12,13,14]),surfaceM:new Float32Array([10,11,12,11,12,13,12,13,14])};
it('retains native terrain positions and slope lighting in the existing WebGL renderer',()=>{expect(adapter).not.toBeNull();const mesh=adapter!.rendererMesh(tile,{eastingM:500000,northingM:4000000,heightM:0});expect([...mesh.positions.slice(0,6)]).toEqual([0,10,0,1,11,0]);expect(mesh.indices.length).toBe(24);expect(mesh.normals[1]).toBeGreaterThan(0);expect(mesh.chunks[0].maximum).toEqual([2,14,2]);});
it('keeps unknown surface holes and never manufactures a camera frame pose',()=>{expect(adapter).not.toBeNull();const missing={...tile,surfaceM:new Float32Array(9).fill(NaN)};expect(adapter!.rendererMesh(missing,{eastingM:0,northingM:0,heightM:0},'surface').indices.length).toBe(0);expect(adapter!.cameraContext({calibration:{validated:true}},null,{altitudeDatum:'EGM96'},1000).poseBracketed).toBe(false);});
it('withholds scene geometry when timing, datum or calibration is absent',()=>{expect(adapter).not.toBeNull();expect(adapter!.registeredPolygons({camera:{},manifest:null,tiles:[],now:1000,telemetry:{},viewport:{x:0,y:0,width:640,height:480}})).toMatchObject({ready:false,polygons:[]});});

import {latLonToUtm} from 'yonder-core/terrain';
const calibration={id:'reviewed',cameraId:'elp',profileId:'fixed',validated:true,width:1280,height:960,fx:600,fy:600,cx:640,cy:480,distortion:{model:'brown-conrady',k1:0,k2:0,p1:0,p2:0,k3:0},bodyToCamera:[0,1,0,0,0,1,1,0,0],cameraOffsetBodyM:[0,0,0],mirrorX:false,rotation:0,residualPx:1,maxResidualPx:2,timingVerified:true,maxTimeErrorMs:20};
const camera={id:'elp',profileId:'fixed',calibration,frameCaptureMs:1000,poseTimeMs:1000,timeErrorMs:1,poseBracketed:true,framePose:{lat:35.9607874,lon:-83.3668696,altitudeM:400,headingDeg:0,pitchDeg:0,rollDeg:0}};
const manifest={verticalDatum:'EGM96',verticalTransform:{verified:true},horizontalCrs:{zone:17}};
const smallTile=(lat:number,lon:number,height:number)=>{const p=latLonToUtm(lat,lon,17);return {descriptor:{id:'measured',level:0,columns:2,rows:2,spacingM:1,originEastingM:p.eastingM-.5,originNorthingM:p.northingM+.5},groundM:new Float32Array(4).fill(height),surfaceM:new Float32Array(4).fill(height)}};
it('renders validated camera scene geometry with UTM convergence corrected',()=>{const result=adapter!.registeredPolygons({camera,manifest,tiles:[smallTile(camera.framePose.lat,camera.framePose.lon,300),smallTile(camera.framePose.lat+.001,camera.framePose.lon,400)],now:1000,telemetry:{altitudeDatum:'EGM96'},viewport:{x:0,y:0,width:1280,height:960}});expect(result.ready).toBe(true);expect(result.polygons).toHaveLength(1);expect(result.polygons[0].level).toBe('warning');expect(result.polygons[0].points.reduce((sum,p)=>sum+p.x,0)/4).toBeCloseTo(640,1)});
it('does not announce registration when tiles or real timestamps are missing',()=>{const args={camera,manifest,tiles:[],now:1000,telemetry:{altitudeDatum:'EGM96'},viewport:{x:0,y:0,width:1280,height:960}};expect(adapter!.registeredPolygons(args)).toMatchObject({ready:false,polygons:[]});expect(adapter!.registeredPolygons({...args,camera:{...camera,frameCaptureMs:null}})).toMatchObject({ready:false,polygons:[]})});

it('excludes visual-only coarse tiles from registered warning geometry',()=>{const tile=smallTile(camera.framePose.lat,camera.framePose.lon,400);tile.descriptor.level=2;expect(adapter!.registeredPolygons({camera,manifest,tiles:[tile],now:1000,telemetry:{altitudeDatum:'EGM96'},viewport:{x:0,y:0,width:1280,height:960}})).toMatchObject({ready:false,polygons:[]})});
